Mappingtool/Solution/WebApp/MappingToolV2/MappingToolV2/Models/ServiceMappingtool.cs
using Microsoft.Azure.Cosmos.Table;
using System;
using System.Collections.Generic;
using System.Web;

namespace MappingToolV2.Models
{
    public class listrbacmapping : TableEntity
    {
        public string Mapping { get; set; }
        public string RBACID { get; set; }
        public string RBACPerm { get; set; }
        public string PermAssign { get; set; }
    }

    public class listrbacpermconfig : TableEntity
    {
        public string AADGroupID { get; set; }
        public string AADGroupName { get; set; }
        public string ADGroupDN { get; set; }
        public string ADGroupName { get; set; }
        public string ADGroupSID { get; set; }
        public string ADGroupuSNChanged { get; set; }
        public string AzureRG { get; set; }
        public string MarkedasDelete { get; set; }
        public string RBACPermID { get; set; }
        public string RBACPermName { get; set; }
        public string SubscriptionID { get; set; }
        public string Validatet { get; set; }
    }

    public class listazurerbacroles
    {
        public string RBACID { get; set; }

        public string RBACValue { get; set; }
    }

    public class listarchivconfig : TableEntity
    {
        public string BackupData { get; set; }
    }

    public class listsubscriptions : TableEntity
    {
        public string SubMapping { get; set; }
    }

    public class listmappingtoolconfig : TableEntity
    {
        public string AllowtoChange { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public string Description { get; set; }
    }

    public class listmessagequeue
    {
        public string Queue { get; set; }
        public string MsgCount { get; set; }

    }

    public class listrunnbookstate
    {
        public string RunnbookName { get; set; }
        public string CurrentState { get; set; }
        public string LastState { get; set; }
        public string FaildCount { get; set; }
        public string SuccessCount { get; set; }
    }

    public class listsrgnew
    {
        public IEnumerable<listrbacmapping> RbacConfig { get; set; }
        public IEnumerable<listsubscriptions> Subscriptions { get; set; }
        public IEnumerable<listazuretags> Tags { get; set; }
        public IEnumerable<listazurergs> RGs { get; set; }
        public IEnumerable<listazurergreqconfigs> RGDefConfigs { get; set; }
    }

    public class listexistrg : TableEntity
    {
        public string RGName { get; set; }
        public string Perm { get; set; }
        public string SubscriptionID { get; set; }
    }

    public class listazurergs
    {
        public string RGName { get; set; }
        public string RGRBACPermTagValue { get; set; }
        public string RGSubscription { get; set; }
    }

    public class listazuretags
    {
        public string TagName { get; set; }
        public string TagValue { get; set; }
    }

    public class listazurergreqconfigs
    {
        public string RGPrefix { get; set; }
    }

    public class ServiceMappingtoolToolConfiguration
    {
       
    }

    public class ServiceMappingtoolMarkedAsDelete
    {

    }
}

Mappingtool/Solution/WebApp/MappingToolV2/MappingToolV2/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MappingToolV2.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Contact()
        {

            return View();
        }

        public ActionResult Architecture()
        {
            return View();
        }

        public ActionResult Workflows()
        {
            return View();
        }

        public ActionResult State()
        {
            return View();
        }
    }
}

Mappingtool/Solution/WebApp/MappingToolV2/MappingToolV2/Controllers/ServiceMappingToolController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MappingToolV2.Controllers
{
    public class ServiceMappingToolController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult State()
        {
            return View();
        }
    }
}

Mappingtool/Solution/WebApp/MappingToolV2/MappingToolV2/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Mappingtool/Solution/WebApp/MappingToolV2/MappingToolV2/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Mappingtool/Solution/WebApp/MappingToolV2/MappingToolV2/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Mappingtool/Solution/WebApp/MappingToolV2/MappingToolV2/Views/ServiceMappingtool/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    Layout = "~/Views/Shared/_Layout_MappingTool.cshtml";
}

<div class="jumbotron MTHeaderStyle">
    <h1>Azure Mappingtool</h1>
    <p class="lead">
        Azure Mappingtool is a free solution hosted in Microsoft Azure.<br />
        This tool is based on Azure PaaS services and will help you to <br />
        administrate and automate the RG deployment and also the permission assignment.
        To get more information about Azure and their services klick on the link:
    <p>
        <a href="https://www.azure.com" target="_blank" class="btn btn-success">Learn more &raquo;</a>
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Architecture</h2>
        <p>
            When I'm started with the development, I had the following requirements:
            <ul>
                <li>Only use PaaS and SaaS services</li>
                <li>Zentral deployment</li>
                <li>Decoupled architecture</li>
            </ul>
            Klick on the link below, to see a high level architecture design.
        </p>
        <p>
            <a class="btn btn-dark" href="@Url.Action("Architecture", "Home")" target="_blank">Architecture &raquo;</a>
        </p>
    </div>
    <div class="col-md-4">
        <h2>Workflows</h2>
        <p>
            Depending on the workflow, the execution will be triggerd by:
            <ul>
                <li>LogicApp</li>
                <li>Script based</li>
                <li>Event based</li>
            </ul>

            To get an overview the workflows, klick on "Learn more".
        </p>
        <p>
            <a class="btn btn-dark" href="@Url.Action("Workflows", "Home")" target="_blank">Learn more &raquo;</a>
        </p>
    </div>
    <div class="col-md-4">
        <h2>Source</h2>
        <p>
            The application is based on <a href="https://de.wikipedia.org/wiki/Open_Source" target="_blank">Open Source</a>. <br />
            The whole source code could be found on my GitHub account.<br />
            Klick on "Get code" to view the whole source code.
        </p>
        <p><a class="btn btn-dark" href="https://github.com/Lagler-Gruener/AzureSolutions/tree/master/Mappingtool" target="_blank">Get code &raquo;</a></p>
    </div>
</div>

Mappingtool/Solution/WebApp/MappingToolV2/MappingToolV2/Views/ServiceMappingtool/State.cshtml
@{
    ViewBag.Title = "State";
    Layout = "~/Views/Shared/_Layout_MappingTool.cshtml";
}

<script type="text/javascript">
    $(function () {
        $('#btnreloadgrid').click(function () {
            MVCGrid.reloadGrid('MappingQueueMessages');
            MVCGrid.reloadGrid('RBACConfigAAD');
            MVCGrid.reloadGrid('RBACConfigRBAC');
            MVCGrid.reloadGrid('MappingToolRunbookState');
        });
    });
</script>

<div class="jumbotron MTHeaderStyle">
    <h1>App state</h1>
    <p class="lead">
        In that section you'll get an overview about the whole <br />
        application state.
        Includet are:
        <ul>
            <li>
                Current, last as well failed and success state about all runbooks
            </li>
            <li>
                How many messages are in the queues
            </li>
            <li>
                The current RBAC (Azure AD and Azure RG) configuration
            </li>
        </ul>
    </p>

    @using (Html.BeginForm())
    {
        <div style="text-align:right">
            <button class="btn btn-success" id="btnreloadgrid">Reload</button>
        </div>
    }
</div>

@using (Html.BeginForm())
{
    <center>
        <div class="MTGridSizeFull">
            <div style="text-align:right">
                @Html.ValidationSummary(false, "", new { @class = "text-danger" })
            </div>
            <div class="well MTGridHeader">
                <div class="form-inline" style="width:100%; position:relative">
                    <div class="form-group" style="padding-right:10px">
                        <h4>Azure Automation Runbooks state</h4>
                    </div>
                </div>
            </div>
            <div style="padding-top:20px">
                @Html.MVCGrid("MappingToolRunbookState")
            </div>

            <div style="padding-top:40px">
            </div>
            <div class="well MTGridHeader">
                <div class="form-inline" style="width:100%; position:relative">
                    <div class="form-group" style="padding-right:10px">
                        <h4>Messages in Azure storage queue</h4>
                    </div>
                </div>
            </div>
            <div style="padding-top:20px">
                @Html.MVCGrid("MappingQueueMessages")
            </div>

            <div style="padding-top:40px">
            </div>
            <div class="well MTGridHeader">
                <div class="form-inline" style="width:100%; position:relative">
                    <div class="form-group" style="padding-right:10px">
                        <h4>Azure AD Permissions</h4>
                    </div>
                </div>
            </div>
            <div style="padding-top:20px">
                @Html.MVCGrid("RBACConfigAAD")
            </div>

            <div style="padding-top:40px">
            </div>
            <div class="well MTGridHeader">
                <div class="form-inline" style="width:100%; position:relative">
                    <div class="form-group" style="padding-right:10px">
                        <h4>Azure RG Permissions</h4>
                    </div>
                </div>
            </div>
            <div style="padding-top:20px">
                @Html.MVCGrid("RBACConfigRBAC")
            </div>
        </div>
    </center>
}

Mappingtool/Solution/WebApp/MappingToolV2/MappingToolV2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>   
    <div class="container body-content">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="@Url.Action("Index", "Home")">Services</a>

            <div class="collapse navbar-collapse navbar navbar-light bg-light" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("Index", "Home")">Home</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Services
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="nav-link" href="@Url.Action("Index", "ServiceMappingTool")">MappingTool</a>                            
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1">Contact</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Mappingtool/Solution/WebApp/MappingToolV2/MappingToolV2/Views/Shared/_Layout_MappingTool.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container body-content">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Mappingtool Admin</a>

            <div class="collapse navbar-collapse navbar navbar-light bg-light" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("Index", "Home")">Home</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("State", "ServiceMappingTool")">State</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Services
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="nav-link" href="@Url.Action("Index", "ServiceMappingTool")">MappingTool</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Admin tools
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="nav-link" href="@Url.Action("AzureRG", "AdminTools")" tabindex="-1">Manage Azure RGs</a>
                            <div class="dropdown-divider"></div>
                            <a class="nav-link" href="@Url.Action("RBACMarkedasDelete", "AdminTools")" title="Azure RG permissions marked as delete">Perm MAD</a>
                            <div class="dropdown-divider"></div>
                            <a class="nav-link" href="@Url.Action("MappingToolIssues", "AdminTools")" style="pointer-events:none; cursor:default">Tool Issues</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Tool Configuration
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("MappingToolConfig", "ToolConfiguration")">Global Configuration</a>
                            <a class="dropdown-item" href="@Url.Action("Subscriptions", "ToolConfiguration")">Global Subscriptions</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="@Url.Action("RBACMapping", "ToolConfiguration")">RBAC mapping</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="@Url.Action("RBACArchiv", "ToolConfiguration")">RBAC Archiv</a>
                        </div>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1">Contact</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    <script src="~/MVCGridHandler.axd/script.js"></script>
</body>
</html>